title: Cloud Networking as Code Slack Signup
email: email@example.com
description: ...description...
domain: cloud-networking-as-code.github.io
url: https://cloud-networking-as-code.github.io/
github_username: cloud-networking-as-code

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
