title: Cloud Networking as Code Slack Signup
email: andy@andytaylor.dev
description: Join the Cloud Networking as Code Slack Workspace
domain: cloud-networking-as-code.github.io
url: https://cloud-networking-as-code.github.io/
github_username: cloud-networking-as-code

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
